### ISSUE TITLE
优化css中的font-face以优先使用本地字体

### ISSUE THREAD

**Issue by hizzgdev** [wc-one/cn-font#1]
以楷体为例，源码中的定义如下:

```css
@font-face {
    font-family: 'FZKai-Z03S';
    font-display: block;
    src: url('L1_7684_256.woff2') format('woff2');
    unicode-range: ...;
}
```

当本地安装的有 FZKai-Z03S 字体时, 浏览器（Chrome Version 109.0.5414.119 ）还是会下载远程的 woff2 字体，不知道这个加载顺序是不是 CSS 的规范，不过加载远程字体确实会有明显卡顿。

我试了一下，如果把 local() 放在 src 的首位好像可以避免下载远程字体，如下所示。

```css
@font-face {
    font-family: 'FZKai-Z03S';
    font-display: block;
    src: local("FZKai-Z03S"), url('L1_7684_256.woff2') format('woff2');
    unicode-range: ...;
}
```

不知这种做法在本项目中是否合理，请作者考虑一下。

另外，不知作者是如何把 ttf 转成 woff2 的，是需要手动分类整理吗？
另外2，个人觉得这个项目很有意义，字体公司应该借鉴并推出官方CDN。

感谢作者的贡献！
